services:
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
